### ISSUE TITLE
Investigate NATS Jetstream

### ISSUE THREAD

**Issue by alejandrogr** [konstellation-io/kre-runners#65]
## Why?

We are experiencing some issues in different projects related to the idle time of some nodes and the NATS disconnection issues. 

## What?

We want to investigate if the NATs Jetstream persistence system is better than the core NATs and if it works well with our environment. 

As we recently updated the NATs python library to the latest version, maybe is a good moment to check if we should move to this system.

**Comment by ixjosemi** [comment]
### When to use Jetstream vs Core NATs

Streaming is ideal when:
- A historical record of a stream is required. This is when a replay of data is required by a consumer.
- The last message produced on a stream is required for initialization and the producer may be offline.
- A-priori knowledge of consumers is not available, but consumers must receive messages. This is often a false assumption.
- Data producers and consumers are highly decoupled. They may be online at different times and consumers must receive messages.
- The data in messages being sent have a lifespan beyond that of the intended application lifespan.
- Applications need to consume data at their own pace.
- You want de-coupled flow control between the publishers and the consumers of the stream
- You need 'exactly-once' quality of service with de-duplication of publications and double-acknowledged consumption

Note that no assumptions should ever be made of who will receive and process data in the future, or for what purpose.

Using core NATS is ideal for the fast request path for scalable services where there is tolerance for message loss or when applications themselves handle message delivery guarantees. These include:
- Service patterns where there is a tightly coupled request/reply
- A request is made, and the application handles error cases upon timeout
(resends, errors, etc). __Relying on a messaging system to resend here is
considered an anti-pattern.__
- Where only the last message received is important and new messages will
be received frequently enough for applications to tolerate a lost message.
This might be a stock ticker stream, frequent exchange of messages in a
service control plane, or device telemetry.
- Message TTL is low, where the value of the data being transmitted degrades
or expires quickly.
- The expected consumer set for a message is available a-priori and consumers
are expected to be live. The request/reply pattern works well here or
consumers can send an application level acknowledgement.
- Control plane messages.


https://docs.nats.io/using-nats/developer/develop_jetstream
